### PR TITLE
[wip] Release Version 1.0.0

### PR DESCRIPTION
**Pull request by ProjectBarks**
### Overview
A substantial part of this codebase is overhead. Most can be reused throughout other Autodesk integrations and maybe even other C# integrations. Currently, oauth, export, and upload all work with ion conversion issues with FBX. The conversion issues have been fixed in the latest version of FBX2GLTF but a new release is pending. When available, conversion without textures will be possible. Discussion around handling missing textures is still pending as well.

### Features
- Oauth --> Creates a Oauth server for token creation. A response UI for denial and acceptance are present. 
- Upload --> Shows dialog and uploads to Cesium ion. 

### Known Bugs
- FBX fails to tile in Cesium ion
- Help button is not yet linked

### Installation
1. Clone the repository `git clone git@github.com:AnalyticalGraphicsInc/cesium-ion-revit-add-in.git`
1. Open Project in Visual Studio
1. Click run

### Usage
1. Open any model within Revit
1. In the `View` Ribbon Tab click `3D View`
1. Navigate to `Add-ins` Ribbon Tab
1. Under the `Cesium ion` panel, click Sign-In and complete Oauth process
1. Navigate back to  `Cesium ion` panel and click Upload
1. Fill in `Name` field of the Upload Dialog
1. Click Upload

### CODE REVIEW

**Comment by mramato** [comment]
Is there a specific reason we are targeting .NET 4.7.x and not 4.5?  I think 4.5 is the standard lowest common denominator so we can be sure everything the user needs is on their system.  I couldn't build this out of the box without download 4.7 support.

**Comment by mramato** [comment]
It took me a second to realize I had to hit sign-in before doing uploading, why can't we just have the upload button perform a sign-in if the user isn't already signed in?  Seems much more user friendly to me.

**Comment by mramato** [comment]
Is it not possible to add ion as an option to the Export panel?

**Comment by mramato** [comment]
Is this just an HTML page?

image

The panel is a little clunky, how much control do we have over it?

In general, can you provide a paragraph that talks about the moving parts here?  For me to review it I need to understand what classes do what and how it all fits together.

**Comment by mramato** [comment]
Also please provide a breakdown of what third-party libraries we are using and why, i.e. is it something we picked or pushed on us by Autodesk?

**Comment by mramato** [comment]
General functionality seems good, just want to iron out the UX workflow a bit and then I'll dig into the code (once I hear back from you regarding my questions).

Thanks @ProjectBarks!

**Comment by mramato** [comment]
The SketchUP plugin has some decent HTML dialogs for the upload, if you want to check that out (depending on how much control we have).  SketchUp also has some specific browser quirks, but some of the basic stuff might be reusable: https://github.com/AnalyticalGraphicsInc/cesium-ion-sketchup-extension/blob/master/src/cesium_ion/dialog.html

**Comment by ProjectBarks** [comment]
> Is there a specific reason we are targeting .NET 4.7.x and not 4.5? I think 4.5 is the standard lowest common denominator so we can be sure everything the user needs is on their system. I couldn't build this out of the box without download 4.7 support.

This was best practices I found in tutorials. Also I found `.NET Framework 4.5 and later versions are backward-compatible with apps that were built with earlier versions of the .NET Framework` so I think I am going to stick with it.

> It took me a second to realize I had to hit sign-in before doing uploading, why can't we just have the upload button perform a sign-in if the user isn't already signed in? Seems much more user friendly to me.

I can't make UI calls after rejoining the main threads in OAuth -- IE trying to get the upload dialog to show. I think the Engineering time of figuring out a hack vs doing it the way we are doing now is minimal.

> Is it not possible to add ion as an option to the Export panel?

No

> Is this just an HTML page?

It's Windows UI. I could probably port it to HTML if we really wanted but I do not think the UI look significantly different. Also, we can then use the applications themeing for UI components to feel more native. 
image
I don't feel strongly either way but I am not sure that a change is worth it.

> Also please provide a breakdown of what third-party libraries we are using and why, i.e. is it something we picked or pushed on us by Autodesk?

Flurl for making HTTP requests easy. EmbedIO for a HTTP Server. AWS for AWS.

**Comment by ProjectBarks** [comment]
Don't look at the code too hard there is some big changes coming in.

**Comment by ProjectBarks** [comment]
@mramato

**Comment by mramato** [comment]
> It's Windows UI.

What is index.html for then?  I see the xaml now, that's fine. I'm just trying to understand the moving parts here, please post a comment with some details of the moving parts.

**Comment by ProjectBarks** [comment]
index.html is the response to oauth

**Comment by ProjectBarks** [comment]
image

**Comment by mramato** [comment]
There appear to be missing assembly references, I can't build.
image

**Comment by mramato** [comment]
```
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\mamato\.nuget\packages\revit_all_main_versions_api_x64\2020.0.0\lib\net47\RevitAPI.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\mamato\.nuget\packages\revit_all_main_versions_api_x64\2020.0.0\lib\net47\RevitAPIUI.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\mamato\.nuget\packages\revit_all_main_versions_api_x64\2020.0.0\lib\net47\UIFramework.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.
```

We probably should target x64 instead of AnyCPU, Revit is x64 only

**Comment by mramato** [comment]
Also received this error after building: (I used Release mode, not sure if that matters)

image

**Comment by ProjectBarks** [comment]
@mramato It is probably fine. Its only used for reference and doesn't actually have a impact on the build process. When you target your system version of Revit this error goes away.

**Comment by ProjectBarks** [comment]
Clear our your `%APPDATA%/Autodesk/Revit/Addins/` to fix that problem

**Comment by ProjectBarks** [comment]
The button unlocks the second the window is refocused. It is a limitation of how Revit redraws the UI.

**Comment by mramato** [comment]
> @mramato It is probably fine. Its only used for reference and doesn't actually have a impact on the build process. When you target your system version of Revit this error goes away.

I'm not sure what you're referencing here.

**Comment by ProjectBarks** [comment]
```
```

**Comment by ProjectBarks** [comment]
Updated comment.

**Comment by mramato** [comment]
> Updated comment.

It's good practice to only target the supported architecture, so please update the project configuration.

**Comment by mramato** [comment]
It's a little picky, but the edit controls on the upload dialog look just a few pixels shorter than standard control height.

Does it make sense to have the WebP option given textures most often won't work?

**Comment by ProjectBarks** [comment]
Closing this PR for revit

**Pull request closed without merging**
